name: CI

on:
  push:
    branches: [ develop ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Develop
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
      
      - name: Install Dependencies
        run: yarn
        
      - name: build
        run: yarn build
        env:
          CACHE_CONNECTIONSTRING: ${{ secrets.CACHE_CONNECTIONSTRING }}
          CACHE_EXPIRETIMEINSECONDS: ${{ secrets.CACHE_EXPIRETIMEINSECONDS }}
          CACHE_HASHKEY: ${{ secrets.CACHE_HASHKEY }}
          MAIL_ACTIVATIONSUBJECT: ${{ secrets.MAIL_ACTIVATIONSUBJECT }}
          MAIL_SENDERNAME: ${{ secrets.MAIL_SENDERNAME }}
          MAIL_SENDERMAIL: ${{ secrets.MAIL_SENDERMAIL }}
          MAIL_APIKEY: ${{ secrets.MAIL_APIKEY }}
          MAIL_APPLOGO: ${{ secrets.MAIL_APPLOGO }}
          TYPEORM_TYPE: ${{ secrets.TYPEORM_TYPE }}
          TYPEORM_HOST: ${{ secrets.TYPEORM_HOST }}
          TYPEORM_PORT: ${{ secrets.TYPEORM_PORT }}
          TYPEORM_USERNAME: ${{ secrets.TYPEORM_USERNAME }}
          TYPEORM_PASSWORD: ${{ secrets.TYPEORM_PASSWORD }}
          TYPEORM_DATABASE: ${{ secrets.TYPEORM_DATABASE }}
          TYPEORM_ENTITIES: ${{ secrets.TYPEORM_ENTITIES }}
          TYPEORM_MIGRATIONS: ${{ secrets.TYPEORM_MIGRATIONS }}
          TYPEORM_CLI_MIGRATIONSDIR: ${{ secrets.TYPEORM_CLI_MIGRATIONSDIR }}
          TYPEORM_CACHE_TYPE: ${{ secrets.TYPEORM_CACHE_TYPE }}
          TYPEORM_CACHE_OPTIONS_HOST: ${{ secrets.TYPEORM_CACHE_OPTIONS_HOST }}
          TYPEORM_CACHE_OPTIONS_PORT: ${{ secrets.TYPEORM_CACHE_OPTIONS_PORT }}
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.QA_SSH_HOST }}
          username: ${{ secrets.QA_SSH_USER }}
          port: ${{ secrets.QA_SSH_PORT }}
          key: ${{ secrets.QA_SSH_KEY }}
          passphrase: ${{ secrets.QA_SSH_PASSPHRASE }}
          source: "."
          target: "/var/www/html/memorizou/mail-sender"
          